"use client";
import {useLocale,LanguagePicker} from './locale';
import {useEffect,useState} from 'react';
import {MapPin,Download,Check,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {available,cities} from '@/lib/workflows';
import {propertyLabels,certificates} from '@/lib/domain';
export const money=(n:number)=>new Intl.NumberFormat('ru-KZ').format(n)+' ₸';
export function CityPicker({city,busy,onChange}:any){const {t,locale}=useLocale();return <div className="city-picker"><MapPin size={16}/><Select value={city} disabled={busy} onValueChange={onChange}><SelectTrigger aria-label={t("Город для проверки наличия")}><SelectValue/></SelectTrigger><SelectContent>{cities.map(city=><SelectItem key={city} value={city}>{t(city)}</SelectItem>)}</SelectContent></Select></div>}
export function PendingAction({pending,busy,onConfirm,onCancel}:any){const {t,locale}=useLocale();
 if(!pending)return null;const lines=pending.lines||[{product:pending.product,count:pending.count,after:pending.count,before:0}];const remove=pending.kind==='remove',set=pending.kind==='set';
 return <div className="confirm"><div className="eyebrow">{t("НУЖНО ВАШЕ ПОДТВЕРЖДЕНИЕ")}</div><p>{remove?t('Удалить товар из корзины?'):set?t('Изменить количество?'):t('Добавить выбранные позиции?')}{!remove&&<><br/><span className="subtle">{t(pending.city||'Все склады')}{t(" · демонстрационная корзина")}</span></>}</p>{lines.map((l:any)=><div className="pending-line" key={l.product.id}><strong>{l.product.name}</strong>{l.product.warning&&<p className="warning">{t(l.product.warning)}</p>}<p>{remove?t(`${l.before} шт. → удалить`):set?t(`${l.before} → ${l.after} шт. · ${money(l.after*l.product.price)}`):t(`+${l.count} шт. × ${money(l.product.price)} = ${money(l.count*l.product.price)}`)}</p></div>)}{!remove&&<p><b>{set?t('Сумма позиции: '):t('Сумма добавления: ')}{money(lines.reduce((s:number,l:any)=>s+(set?l.after:l.count)*l.product.price,0))}</b></p>}<div className="button-row"><Button disabled={busy} onClick={onConfirm}>{remove?t('Да, удалить'):set?t('Да, изменить'):t('Да, добавь')}</Button><Button variant="outline" disabled={busy} onClick={onCancel}>{t("Отмена")}</Button></div></div>
}
export function Comparison({data,city,onClose}:any){const {t,locale}=useLocale();
 const ps=data?.comparison||[];const rows=[{name:'Цена за единицу',values:ps.map((p:any)=>money(p.price))},{name:'Наличие · '+city,values:ps.map((p:any)=>available(p,city)+' шт.')},...['TORGOVAYA_MARKA','NOMINALNYY_TOK','KOLICHESTVO_POLYUSOV','NOMINALNOE_NAPRYAZHENIE','NOMINALNAYA_OTKLYUCHAYUSHCHAYA_SPOSOBNOST','TIP_USTANOVKI','KRATNOST_MIN'].map(k=>({name:propertyLabels[k],values:ps.map((p:any)=>String(p.properties[k]??'Не указано'))})),{name:'Сертификаты в API',values:ps.map((p:any)=>certificates(p).length?'Есть ссылки':'Не предоставлены')}];
 return <Dialog open={!!data} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>{t("Сравнение товаров")}</DialogTitle><DialogDescription>{t("Выделены различающиеся строки. Совпадение значений не гарантирует техническую взаимозаменяемость.")}</DialogDescription></DialogHeader><p className="subtle">{data?.hasSnapshot?t('Часть данных не удалось обновить: для этих товаров показан сохранённый снимок от ')+new Date(data.snapshotAt).toLocaleDateString('ru-RU'):t('Цена и остаток проверены: ')+(data?.checkedAt?new Date(data.checkedAt).toLocaleTimeString('ru-RU'):'')}</p><Table className="comparison-table"><TableHeader><TableRow><TableHead>{t("Параметр")}</TableHead>{ps.map((p:any)=><TableHead key={p.id}><span className="sku">{p.article} · {p.dataSource==='snapshot'?t('сохранённые данные'):t('проверено в API')}</span><h3>{p.name}</h3>{p.warning&&<p className="warning">{t(p.warning)}</p>}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={t(r.name)} className={new Set(r.values).size>1?'different':''}><TableCell>{t(r.name)}</TableCell>{r.values.map((v:string,i:number)=><TableCell key={i}>{t(v)}</TableCell>)}</TableRow>)}</TableBody></Table></DialogContent></Dialog>
}
export function Specification({open,text,onText,rows,onRows,onClose,onParse,onStage,busy,error,city}:any){const {t,locale}=useLocale();
 function update(index:number,patch:any){onRows(rows.map((r:any)=>r.index===index?{...r,...patch}:r))}
 const selected=rows.filter((r:any)=>r.checked&&r.productId);
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="wide-dialog specification-dialog"><DialogHeader><DialogTitle>{t("Подбор по спецификации")}</DialogTitle><DialogDescription>{t("Проверьте каждую строку, товар и количество. Ничего не добавляется автоматически.")}</DialogDescription></DialogHeader><label htmlFor="spec-text">{t("Артикул или название; количество")}</label><textarea id="spec-text" disabled={busy} className="spec-input" value={text} onChange={e=>onText(e.target.value)} maxLength={12000} placeholder={'200300285_; 2\n200300274_; 1'}/>{text.length>=12000&&<p className="warning">{t("Показаны первые 12000 символов. Если документ длиннее, загрузите оставшуюся часть отдельно.")}</p>}<div className="toolbar"><Button disabled={busy||!text.trim()} onClick={onParse}>{t("Разобрать строки")}</Button><span className="subtle">{t("До 60 строк · ")}{t(city)}</span></div>{error&&<p className="warning" role="alert">{t(error)}</p>}{rows.length>0&&<div className="spec-rows">{rows.map((r:any)=><div className="spec-row" key={r.index}><div className="spec-row-title"><Checkbox checked={!!r.checked} disabled={!r.productId||busy} aria-label={t('Выбрать строку ')+(r.index+1)} onCheckedChange={v=>update(r.index,{checked:!!v})}/><span><b>{r.index+1}.</b> {r.line}</span></div>{!r.candidates.length?<p className="warning">{t("Не найдено в выборке. Оставьте строку для менеджера.")}</p>:<div className="spec-row-fields"><Select value={r.productId?String(r.productId):undefined} disabled={busy} onValueChange={v=>update(r.index,{productId:Number(v),checked:false})}><SelectTrigger aria-label={t('Товар в строке ')+(r.index+1)}><SelectValue placeholder={t("Выберите подходящий товар")}/></SelectTrigger><SelectContent>{r.candidates.map((p:any)=><SelectItem key={p.id} value={String(p.id)}>{p.name} · {available(p,city)}{t(" шт.")}</SelectItem>)}</SelectContent></Select><label>{t("Количество")}<input type="number" min="1" step="1" disabled={busy} value={r.count??''} aria-label={t('Количество в строке ')+(r.index+1)} onChange={e=>update(r.index,{count:e.target.value===''?null:Number(e.target.value)})}/></label></div>}{r.candidates.length>0&&<p className="subtle">{r.status==='exact'?t('Артикул совпал.'):t('Подбор по словам — нужна проверка.')} {r.count===null?t('Количество не распознано: укажите вручную.'):''}</p>}</div>)}</div>}<div className="dialog-bottom"><span>{t("Выбрано: ")}{selected.length} / {rows.length}</span><Button disabled={busy||!selected.length||selected.some((r:any)=>!Number.isSafeInteger(r.count)||r.count<=0)} onClick={()=>onStage(selected.map((r:any)=>({id:r.productId,count:r.count})))}>{t("Проверить и добавить…")}</Button></div></DialogContent></Dialog>
}
export function CartEditor({product,busy,onSet,onRemove}:any){const {t,locale}=useLocale();const[count,setCount]=useState(String(product.count));useEffect(()=>setCount(String(product.count)),[product.count]);return <div className="cart-line"><h3>{product.name}</h3><p>{product.count}{t(" шт. × ")}{money(product.price)} {product.city?'· '+product.city:''}</p><b>{money(product.count*product.price)}</b><div className="cart-actions"><label className="sr-only" htmlFor={'cart-'+product.id}>{t("Новое количество ")}{product.name}</label><input id={'cart-'+product.id} type="number" min="1" step="1" value={count} onChange={e=>setCount(e.target.value)} disabled={busy}/><Button variant="outline" disabled={busy||!Number.isSafeInteger(Number(count))||Number(count)<=0||Number(count)===product.count} onClick={()=>onSet(Number(count))}>{t("Изменить…")}</Button><Button variant="ghost" disabled={busy} onClick={onRemove} aria-label={t('Удалить ')+product.name}><Trash2 size={16}/></Button></div></div>}
export function Handoff({draft,onChange,onClose}:any){const {t,locale}=useLocale();function download(){const url=URL.createObjectURL(new Blob([draft],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ekt-request.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}return <Dialog open={draft!==null} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>{t("Обращение менеджеру")}</DialogTitle><DialogDescription>{t("Проверьте и отредактируйте текст. Он не отправляется автоматически; скачайте его и передайте менеджеру выбранным вами способом.")}</DialogDescription></DialogHeader><textarea className="handoff-text" aria-label={t("Текст обращения менеджеру")} value={draft||''} onChange={e=>onChange(e.target.value)}/><Button onClick={download} disabled={!draft}><Download size={16}/>{t("Скачать обращение")}</Button></DialogContent></Dialog>}
