"use client";
import {useEffect,useState} from 'react';
import {MapPin,Download,Check,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {available,cities} from '@/lib/workflows';
import {propertyLabels,certificates} from '@/lib/domain';
export const money=(n:number)=>new Intl.NumberFormat('ru-KZ').format(n)+' ₸';
export function CityPicker({city,busy,onChange}:any){return <div className="city-picker"><MapPin size={16}/><Select value={city} disabled={busy} onValueChange={onChange}><SelectTrigger aria-label="Город для проверки наличия"><SelectValue/></SelectTrigger><SelectContent>{cities.map(city=><SelectItem key={city} value={city}>{city}</SelectItem>)}</SelectContent></Select></div>}
export function PendingAction({pending,busy,onConfirm,onCancel}:any){
 if(!pending)return null;const lines=pending.lines||[{product:pending.product,count:pending.count,after:pending.count,before:0}];const remove=pending.kind==='remove',set=pending.kind==='set';
 return <div className="confirm"><div className="eyebrow">НУЖНО ВАШЕ ПОДТВЕРЖДЕНИЕ</div><p>{remove?'Удалить товар из корзины?':set?'Изменить количество?':'Добавить выбранные позиции?'}{!remove&&<><br/><span className="subtle">{pending.city||'Все склады'} · демонстрационная корзина</span></>}</p>{lines.map((l:any)=><div className="pending-line" key={l.product.id}><strong>{l.product.name}</strong>{l.product.warning&&<p className="warning">{l.product.warning}</p>}<p>{remove?`${l.before} шт. → удалить`:set?`${l.before} → ${l.after} шт. · ${money(l.after*l.product.price)}`:`+${l.count} шт. × ${money(l.product.price)} = ${money(l.count*l.product.price)}`}</p></div>)}{!remove&&<p><b>{set?'Сумма позиции: ':'Сумма добавления: '}{money(lines.reduce((s:number,l:any)=>s+(set?l.after:l.count)*l.product.price,0))}</b></p>}<div className="button-row"><Button disabled={busy} onClick={onConfirm}>{remove?'Да, удалить':set?'Да, изменить':'Да, добавь'}</Button><Button variant="outline" disabled={busy} onClick={onCancel}>Отмена</Button></div></div>
}
export function Comparison({data,city,onClose}:any){
 const ps=data?.comparison||[];const rows=[{name:'Цена за единицу',values:ps.map((p:any)=>money(p.price))},{name:'Наличие · '+city,values:ps.map((p:any)=>available(p,city)+' шт.')},...['TORGOVAYA_MARKA','NOMINALNYY_TOK','KOLICHESTVO_POLYUSOV','NOMINALNOE_NAPRYAZHENIE','NOMINALNAYA_OTKLYUCHAYUSHCHAYA_SPOSOBNOST','TIP_USTANOVKI','KRATNOST_MIN'].map(k=>({name:propertyLabels[k],values:ps.map((p:any)=>String(p.properties[k]??'Не указано'))})),{name:'Сертификаты в API',values:ps.map((p:any)=>certificates(p).length?'Есть ссылки':'Не предоставлены')}];
 return <Dialog open={!!data} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>Сравнение товаров</DialogTitle><DialogDescription>Выделены различающиеся строки. Совпадение значений не гарантирует техническую взаимозаменяемость.</DialogDescription></DialogHeader><p className="subtle">{data?.hasSnapshot?'Часть данных не удалось обновить: для этих товаров показан сохранённый снимок от '+new Date(data.snapshotAt).toLocaleDateString('ru-RU'):'Цена и остаток проверены: '+(data?.checkedAt?new Date(data.checkedAt).toLocaleTimeString('ru-RU'):'')}</p><Table className="comparison-table"><TableHeader><TableRow><TableHead>Параметр</TableHead>{ps.map((p:any)=><TableHead key={p.id}><span className="sku">{p.article} · {p.dataSource==='snapshot'?'сохранённые данные':'проверено в API'}</span><h3>{p.name}</h3>{p.warning&&<p className="warning">{p.warning}</p>}</TableHead>)}</TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.name} className={new Set(r.values).size>1?'different':''}><TableCell>{r.name}</TableCell>{r.values.map((v:string,i:number)=><TableCell key={i}>{v}</TableCell>)}</TableRow>)}</TableBody></Table></DialogContent></Dialog>
}
export function Specification({open,text,onText,rows,onRows,onClose,onParse,onStage,busy,error,city}:any){
 function update(index:number,patch:any){onRows(rows.map((r:any)=>r.index===index?{...r,...patch}:r))}
 const selected=rows.filter((r:any)=>r.checked&&r.productId);
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="wide-dialog specification-dialog"><DialogHeader><DialogTitle>Подбор по спецификации</DialogTitle><DialogDescription>Проверьте каждую строку, товар и количество. Ничего не добавляется автоматически.</DialogDescription></DialogHeader><label htmlFor="spec-text">Артикул или название; количество</label><textarea id="spec-text" disabled={busy} className="spec-input" value={text} onChange={e=>onText(e.target.value)} maxLength={12000} placeholder={'200300285_; 2\n200300274_; 1'}/>{text.length>=12000&&<p className="warning">Показаны первые 12000 символов. Если документ длиннее, загрузите оставшуюся часть отдельно.</p>}<div className="toolbar"><Button disabled={busy||!text.trim()} onClick={onParse}>Разобрать строки</Button><span className="subtle">До 60 строк · {city}</span></div>{error&&<p className="warning" role="alert">{error}</p>}{rows.length>0&&<div className="spec-rows">{rows.map((r:any)=><div className="spec-row" key={r.index}><div className="spec-row-title"><Checkbox checked={!!r.checked} disabled={!r.productId||busy} aria-label={'Выбрать строку '+(r.index+1)} onCheckedChange={v=>update(r.index,{checked:!!v})}/><span><b>{r.index+1}.</b> {r.line}</span></div>{!r.candidates.length?<p className="warning">Не найдено в выборке. Оставьте строку для менеджера.</p>:<div className="spec-row-fields"><Select value={r.productId?String(r.productId):undefined} disabled={busy} onValueChange={v=>update(r.index,{productId:Number(v),checked:false})}><SelectTrigger aria-label={'Товар в строке '+(r.index+1)}><SelectValue placeholder="Выберите подходящий товар"/></SelectTrigger><SelectContent>{r.candidates.map((p:any)=><SelectItem key={p.id} value={String(p.id)}>{p.name} · {available(p,city)} шт.</SelectItem>)}</SelectContent></Select><label>Количество<input type="number" min="1" step="1" disabled={busy} value={r.count??''} aria-label={'Количество в строке '+(r.index+1)} onChange={e=>update(r.index,{count:e.target.value===''?null:Number(e.target.value)})}/></label></div>}{r.candidates.length>0&&<p className="subtle">{r.status==='exact'?'Артикул совпал.':'Подбор по словам — нужна проверка.'} {r.count===null?'Количество не распознано: укажите вручную.':''}</p>}</div>)}</div>}<div className="dialog-bottom"><span>Выбрано: {selected.length} / {rows.length}</span><Button disabled={busy||!selected.length||selected.some((r:any)=>!Number.isSafeInteger(r.count)||r.count<=0)} onClick={()=>onStage(selected.map((r:any)=>({id:r.productId,count:r.count})))}>Проверить и добавить…</Button></div></DialogContent></Dialog>
}
export function CartEditor({product,busy,onSet,onRemove}:any){const[count,setCount]=useState(String(product.count));useEffect(()=>setCount(String(product.count)),[product.count]);return <div className="cart-line"><h3>{product.name}</h3><p>{product.count} шт. × {money(product.price)} {product.city?'· '+product.city:''}</p><b>{money(product.count*product.price)}</b><div className="cart-actions"><label className="sr-only" htmlFor={'cart-'+product.id}>Новое количество {product.name}</label><input id={'cart-'+product.id} type="number" min="1" step="1" value={count} onChange={e=>setCount(e.target.value)} disabled={busy}/><Button variant="outline" disabled={busy||!Number.isSafeInteger(Number(count))||Number(count)<=0||Number(count)===product.count} onClick={()=>onSet(Number(count))}>Изменить…</Button><Button variant="ghost" disabled={busy} onClick={onRemove} aria-label={'Удалить '+product.name}><Trash2 size={16}/></Button></div></div>}
export function Handoff({draft,onChange,onClose}:any){function download(){const url=URL.createObjectURL(new Blob([draft],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='ekt-request.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}return <Dialog open={draft!==null} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="wide-dialog"><DialogHeader><DialogTitle>Обращение менеджеру</DialogTitle><DialogDescription>Проверьте и отредактируйте текст. Он не отправляется автоматически; скачайте его и передайте менеджеру выбранным вами способом.</DialogDescription></DialogHeader><textarea className="handoff-text" aria-label="Текст обращения менеджеру" value={draft||''} onChange={e=>onChange(e.target.value)}/><Button onClick={download} disabled={!draft}><Download size={16}/>Скачать обращение</Button></DialogContent></Dialog>}
