"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ShoppingBag,Zap,Search,Package,ShieldCheck,ExternalLink,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
type Product={id:number;name:string;article:string;price:number;quantity:number;image?:string;url:string;description?:string;properties?:Record<string,unknown>;stores?:{name:string;quantity:number}[];warning?:string};
const money=(n:number)=>new Intl.NumberFormat('ru-KZ').format(n)+' ₸';
export default function Home(){
 const [messages,setMessages]=useState<any[]>([{role:'assistant',text:'Здравствуйте! Помогу найти товар, проверить наличие и разобраться в характеристиках. Напишите артикул или расскажите, что нужно подобрать.'}]);
 const [input,setInput]=useState(''),[products,setProducts]=useState<Product[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[meta,setMeta]=useState<any>(null),[detail,setDetail]=useState<Product|null>(null),[cart,setCart]=useState<any[]>([]),[cartOpen,setCartOpen]=useState(false),[pending,setPending]=useState<any>(null),[qty,setQty]=useState('1');
 const bottom=useRef<HTMLDivElement>(null);
 async function api(body:any){const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d:any=await r.json();if(!r.ok)throw Error(d.error||'Не удалось выполнить запрос');return d}
 function apply(d:any){if(d.products)setProducts(d.products);if(d.cart)setCart(d.cart);if('pending'in d)setPending(d.pending);if(d.text)setMessages(m=>[...m,{role:'assistant',text:d.text,sourceUrl:d.sourceUrl,cartUrl:d.cartUrl}]);if(d.meta)setMeta(d.meta)}
 useEffect(()=>{fetch('/api/assistant').then(r=>r.json()).then((d:any)=>{if(d.error)throw Error(d.error);apply(d)}).catch(e=>setError(e.message));if(location.hash==='#cart')setCartOpen(true);const cb=()=>setCartOpen(location.hash==='#cart');window.addEventListener('hashchange',cb);return()=>window.removeEventListener('hashchange',cb)},[]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages,busy,pending]);
 async function act(body:any){if(busy)return;setBusy(true);setError('');try{apply(await api(body))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function send(text=input){if(!text.trim()||busy)return;setInput('');setMessages(m=>[...m,{role:'user',text}]);await act({action:'chat',message:text})}
 useEffect(()=>{const ctx=(document as any).modelContext;if(!ctx?.registerTool)return;const c=new AbortController();Promise.resolve(ctx.registerTool({name:'search_catalog',description:'Search the EKT sample catalog and display results. Does not modify the cart.',inputSchema:{type:'object',properties:{query:{type:'string',minLength:1,maxLength:1000}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(v:any)=>{if(typeof v?.query!=='string'||!v.query.trim()||v.query.length>1000)throw Error('Invalid query');const d=await api({action:'search',message:v.query});setProducts(d.products);return{products:d.products}}},{signal:c.signal})).catch(()=>{});return()=>c.abort()},[]);
 async function upload(file:File){if(busy)return;setBusy(true);setError('');try{const form=new FormData();form.append('file',file);const r=await fetch('/api/attachment',{method:'POST',body:form});const d:any=await r.json();if(!r.ok)throw Error(d.error);setInput(d.text.slice(0,2000));setMessages(m=>[...m,{role:'assistant',text:'Файл «'+file.name+'» прочитан. Проверьте текст в поле ввода, оставьте нужный артикул или строку спецификации и отправьте запрос. Корзина не изменена.'}])}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function openCart(){setCartOpen(true);history.replaceState(null,'','#cart')}
 return <main className="workspace"><header className="topbar"><a className="brand" href="/"><span className="brandmark"><Zap size={25} fill="currentColor"/></span><span>ЭЛЕКТРОКОМПЛЕКТ<small>КОНСУЛЬТАНТ ПО КАТАЛОГУ</small></span></a><span className="demo-tag">HackAlem AI · прототип</span><Button variant="outline" onClick={openCart}><ShoppingBag/>Корзина <b>{cart.reduce((a,p)=>a+p.count,0)}</b></Button></header>
 <div className="workhead"><div><div className="eyebrow">ПОДБОР ЭЛЕКТРОТЕХНИКИ</div><h1>От вопроса — к нужному товару</h1><p>Характеристики, наличие и варианты замены в одном чате.</p></div><div className="source-note"><ShieldCheck size={20}/><span>Данные ekt.kz<small>{meta?`${meta.count} товаров в выборке`:'Подключаем каталог…'}</small></span></div></div>
 <div className="columns"><section className="chat-panel"><div className="panel-header"><span className="assistant-icon"><Zap size={18}/></span><div><h2>Ваш консультант</h2><p>{meta?.llm?'ИИ + поиск по каталогу':'Поиск и ответы по данным каталога'}</p></div></div><div className="conversation" role="log" aria-live="polite">{messages.map((m,i)=><div key={i} className={'message '+m.role}>{m.role==='assistant'&&<div className="message-label">ЭК · КОНСУЛЬТАНТ</div>}<p>{m.text}</p>{m.sourceUrl&&<a className="store-link" href={m.sourceUrl} target="_blank" rel="noreferrer">Источник: ekt.kz <ExternalLink size={14}/></a>}{m.cartUrl&&<button className="store-link" onClick={openCart}>Перейти в корзину →</button>}</div>)}{messages.length===1&&<div className="suggestions">{['Есть товар 515291?','Подбери автомат Legrand','Какие условия доставки?'].map(t=><button key={t} onClick={()=>send(t)}>{t}<span>↗</span></button>)}</div>}{pending&&<div className="confirm"><div className="eyebrow">НУЖНО ВАШЕ ПОДТВЕРЖДЕНИЕ</div><strong>{pending.product.name}</strong><p>{pending.count} шт. × {money(pending.product.price)} = <b>{money(pending.count*pending.product.price)}</b></p><p>Добавить в демонстрационную корзину?</p><div className="button-row"><Button disabled={busy} onClick={()=>act({action:'confirm',token:pending.token})}>Да, добавь</Button><Button disabled={busy} variant="outline" onClick={()=>act({action:'cancel'})}>Отмена</Button></div></div>}{busy&&<p className="thinking">Проверяю данные…</p>}<div ref={bottom}/></div>{error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Закрыть ошибку"><X size={16}/></button></div>}<form className="composer" onSubmit={e=>{e.preventDefault();send()}}><label htmlFor="question" className="sr-only">Ваш вопрос</label><label className="upload-label">Прикрепить спецификацию или фото<input type="file" accept=".docx,.xlsx,.pdf,.jpg,.jpeg,.csv,.txt" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)upload(file);e.target.value=''}}/></label><textarea id="question" value={input} onChange={e=>setInput(e.target.value)} placeholder="Например: нужен автомат Legrand на 40 А" maxLength={2000} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}}/><div className="composer-bottom"><span>Enter — отправить · Shift+Enter — новая строка</span><Button type="submit" size="icon" disabled={busy||!input.trim()} aria-label="Отправить вопрос"><ArrowUp/></Button></div></form><div className="chat-foot"><ShieldCheck size={14}/> Корзина меняется только после вашего подтверждения</div></section>
 <section className="catalog-panel"><div className="catalog-heading"><div><h2>Товары по вашему запросу</h2><p>{products.length?`${products.length} вариантов · цены в тенге`:'Здесь появятся результаты поиска'}</p></div><Search size={20}/></div><div className="products">{products.map(p=><article key={p.id} className="product"><div className="product-top"><div className="product-image">{p.image?<img src={p.image} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>:<Package size={40}/>}</div><div><span className="sku">АРТ. {p.article}</span><h3>{p.name}</h3><span className={'stock '+(p.quantity>0?'':'none')}>{p.quantity>0?`В наличии · ${p.quantity} шт.`:'Нет в наличии'}</span></div></div><div className="product-bottom"><strong>{money(p.price)}</strong><Button variant="outline" onClick={async()=>{setQty('1');setDetail(p);try{const d=await api({action:'detail',id:p.id});setDetail(d.product)}catch(e:any){setError(e.message)}}}>Подробнее</Button></div></article>)}</div><div className="catalog-note"><ShieldCheck size={18}/><p>Цены и остатки на карточках — снимок каталога{meta?.syncedAt?' от '+new Date(meta.syncedAt).toLocaleDateString('ru-RU'):''}. При добавлении проверяем актуальные данные. Техническую совместимость замены уточняйте у специалиста.</p></div><a href="https://ekt.kz" target="_blank" rel="noreferrer" className="store-link">Открыть полный каталог ekt.kz <ExternalLink size={15}/></a></section></div>
 <Sheet open={!!detail} onOpenChange={v=>{if(!v)setDetail(null)}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Карточка товара</SheetTitle><SheetDescription>Данные каталога ekt.kz</SheetDescription></SheetHeader>{detail&&<div className="sheet-body"><span className="sku">{detail.article} · ID {detail.id}</span><h2>{detail.name}</h2><strong className="detail-price">{money(detail.price)}</strong><p>Доступно: {detail.quantity} шт.</p>{detail.warning&&<p className="warning">{detail.warning}</p>}<p className="description">{detail.description||'Описание не предоставлено.'}</p><h3>Остатки по складам</h3>{detail.stores?.filter(s=>s.quantity>0).map((s,i)=><div key={i} className="spec"><span>{s.name}</span><b>{s.quantity}</b></div>)}<h3>Характеристики</h3>{Object.entries(detail.properties||{}).filter(([k])=>!['CML2_TRAITS','RECOMMEND','IMYAKARTINKI','BRAND_PRIORITY'].includes(k)).map(([k,v])=><div className="spec" key={k}><span>{({NOMINALNYY_TOK:'Номинальный ток',NOMINALNOE_NAPRYAZHENIE:'Напряжение',KOLICHESTVO_POLYUSOV:'Полюсы',TORGOVAYA_MARKA:'Бренд',KRATNOST_MIN:'Кратность',ARTIKULPOSTAVSHCHIKA:'Артикул производителя'} as any)[k]||k}</span><b>{String(v)}</b></div>)}<p className="subtle">Сертификат: {Object.keys(detail.properties||{}).some(k=>/cert|sert/i.test(k))?'см. данные карточки':'ссылка не предоставлена API. Запросите у менеджера.'}</p><a className="store-link" href={detail.url} target="_blank" rel="noreferrer">Карточка на ekt.kz <ExternalLink size={14}/></a><div className="quantity"><label htmlFor="quantity">Количество</label><input id="quantity" type="number" min="1" max={detail.quantity} value={qty} onChange={e=>setQty(e.target.value)}/><Button disabled={busy||detail.quantity<=0} onClick={async()=>{await act({action:'propose',id:detail.id,count:Number(qty)});setDetail(null)}}>Добавить…</Button></div><Button variant="outline" disabled={busy} onClick={()=>{send('Подбери аналог '+detail.id);setDetail(null)}}>Подобрать аналог</Button></div>}</SheetContent></Sheet>
 <Sheet open={cartOpen} onOpenChange={v=>{setCartOpen(v);if(!v)history.replaceState(null,'','#')}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Ваша корзина</SheetTitle><SheetDescription>Демонстрационная корзина. Заказ на ekt.kz не оформляется.</SheetDescription></SheetHeader><div className="sheet-body">{cart.length?cart.map(p=><div className="cart-line" key={p.id}><h3>{p.name}</h3><p>{p.count} шт. × {money(p.price)}</p><b>{money(p.count*p.price)}</b></div>):<p>Корзина пока пуста. Выберите товар и подтвердите добавление в чате.</p>}{cart.length>0&&<div className="total">Итого <b>{money(cart.reduce((s,p)=>s+p.price*p.count,0))}</b></div>}<p className="subtle">Товары не зарезервированы. Для оформления реального заказа обратитесь к менеджеру или используйте сайт магазина.</p><a className="store-link" href="https://ekt.kz" target="_blank" rel="noreferrer">Перейти на ekt.kz <ExternalLink size={14}/></a></div></SheetContent></Sheet>
 </main>
}
