"use client";
import {useState} from 'react';
import {ThumbsUp,ThumbsDown,Download} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {useLocale} from './locale';
export function AnswerRating({message,busy,onRate}:any){const{t}=useLocale();return <div className="answer-rating" role="group" aria-label={t('Оценка ответа')}><button type="button" aria-label={t('Помогло')} aria-pressed={message.rating===1} disabled={busy} onClick={()=>onRate(message.rating===1?null:1)}><ThumbsUp size={14}/></button><button type="button" aria-label={t('Не помогло')} aria-pressed={message.rating===-1} disabled={busy} onClick={()=>onRate(message.rating===-1?null:-1)}><ThumbsDown size={14}/></button>{message.rating&&<span role="status">{t('Спасибо за оценку')}</span>}</div>}
export function ExportSelection({busy,compact=false}:any){const{t,locale,rates}=useLocale();const[working,setWorking]=useState(false),[error,setError]=useState('');async function run(format:'xlsx'|'pdf'){
 setWorking(true);setError('');try{const r=await fetch('/api/selection',{cache:'no-store'});const data:any=await r.json();if(!r.ok)throw Error(data.error);if(!data.rows.length&&!data.unresolved.length)throw Error('Добавьте товары в корзину или загрузите спецификацию.');const mod=await import('@/lib/export-selection');let bytes:Uint8Array;if(format==='xlsx')bytes=mod.selectionXlsx(data,locale,rates);else{const font=await fetch('/fonts/DejaVuSans.ttf');if(!font.ok)throw Error('Не удалось загрузить шрифт PDF.');bytes=await mod.selectionPdf(data,locale,new Uint8Array(await font.arrayBuffer()),rates)}const blob=new Blob([new Uint8Array(bytes)],{type:format==='xlsx'?'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`ekt-selection-${locale}-${new Date(data.generatedAt).toISOString().slice(0,10)}.${format}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e:any){setError(e.message||'Не удалось выполнить запрос.')}finally{setWorking(false)}}
 return <div className={'selection-export'+(compact?' compact':'')}><span className="export-label"><Download size={15}/>{t(compact?'Экспорт':'Скачать подборку')}</span><div><Button variant="outline" size="sm" disabled={busy||working} onClick={()=>run('xlsx')}>Excel</Button><Button variant="outline" size="sm" disabled={busy||working} onClick={()=>run('pdf')}>PDF</Button></div>{working&&<span role="status">{t('Готовим файл…')}</span>}{error&&<p role="alert">{t(error)}</p>}</div>
}
