import {zipSync,strToU8} from 'fflate';
import {translate,type Locale} from './i18n';
import type {Selection} from './selection';
const xml=(s:unknown)=>String(s??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
const note='Цены сохранены при подтверждении корзины; выгрузка не обновляет цены. Это не счёт и не заказ; товары не зарезервированы.';
const sum=(data:Selection)=>data.rows.reduce((a,p)=>a+p.count*p.price,0);
const money=(v:number)=>new Intl.NumberFormat('ru-KZ',{maximumFractionDigits:2}).format(v)+' ₸';
/** Portable OOXML writer: text is always an inline string, never a user-supplied formula. */
export function selectionXlsx(data:Selection,locale:Locale){
 const t=(s:unknown)=>translate(s,locale),enc=(s:string)=>strToU8(s);
 const cell=(ref:string,v:any,style=0,formula?:string)=>`<c r="${ref}" s="${style}"${typeof v==='number'?'':' t="inlineStr"'}>${formula?`<f>${formula}</f>`:''}${typeof v==='number'?`<v>${v}</v>`:`<is><t xml:space="preserve">${xml(v)}</t></is>`}</c>`;
 const row=(n:number,cells:string,height=32)=>`<row r="${n}" ht="${height}" customHeight="1">${cells}</row>`;
 let body=row(1,cell('A1',t('Подборка товаров'),1),30)+row(2,cell('A2',`${t('Дата выгрузки')}: ${new Date(data.generatedAt).toLocaleString(locale==='kk'?'kk-KZ':'ru-KZ',{timeZone:'Asia/Almaty'})} · ${t('Город')}: ${t(data.city)}`),26)+row(3,cell('A3',t(note),5),34)+row(4,cell('A4',t('Товары из каталога приведены на языке источника.'),5),23);
 const headers=['№','Артикул','Наименование','Количество','Цена, ₸','Сумма, ₸','Город','Ссылка на товар'];
 body+=row(6,headers.map((v,i)=>cell(String.fromCharCode(65+i)+'6',t(v),2)).join(''),30);
 data.rows.forEach((p,i)=>{const n=i+7;const vals=[i+1,p.article,p.name,p.count,p.price,p.count*p.price,t(p.city),p.url];body+=row(n,vals.map((v,j)=>cell(String.fromCharCode(65+j)+n,v,j===1?6:j===4||j===5?4:0,j===5?`D${n}*E${n}`:undefined)).join(''),Math.max(42,Math.ceil(p.name.length/45)*15))});
 const totalRow=data.rows.length+7;body+=row(totalRow,cell('C'+totalRow,t('Итого'),2)+cell('F'+totalRow,sum(data),4,data.rows.length?`SUM(F7:F${totalRow-1})`:'0'),30);
 let last=totalRow;
 if(data.unresolved.length){last+=2;body+=row(last,cell('A'+last,t('Проверить с менеджером'),1),28);last++;body+=row(last,cell('A'+last,t('Позиции для уточнения не включены в итоговую сумму.'),5),28);last++;body+=row(last,cell('A'+last,t('Исходная строка'),2)+cell('D'+last,t('Количество'),2)+cell('E'+last,t('Статус'),2));for(const u of data.unresolved){last++;body+=row(last,cell('A'+last,u.line)+cell('D'+last,u.count??'—')+cell('E'+last,t(u.status)),Math.max(35,Math.ceil(u.line.length/50)*15))}}
 const merges=['A1:H1','A2:H2','A3:H3','A4:H4'];if(data.unresolved.length){const a=totalRow+2;merges.push(`A${a}:H${a}`,`A${a+1}:H${a+1}`,`A${a+2}:C${a+2}`,`E${a+2}:H${a+2}`);data.unresolved.forEach((_,i)=>{const n=a+3+i;merges.push(`A${n}:C${n}`,`E${n}:H${n}`)})}
 const sheet=`<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:H${last}"/><sheetViews><sheetView workbookViewId="0" showGridLines="0"><pane ySplit="6" topLeftCell="A7" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${[6,20,55,14,18,20,20,54].map((w,i)=>`<col min="${i+1}" max="${i+1}" width="${w}" customWidth="1"/>`).join('')}</cols><sheetData>${body}</sheetData>${data.rows.length?`<autoFilter ref="A6:H${totalRow-1}"/>`:''}<mergeCells count="${merges.length}">${merges.map(ref=>`<mergeCell ref="${ref}"/>`).join('')}</mergeCells><pageMargins left="0.25" right="0.25" top="0.4" bottom="0.4" header="0.2" footer="0.2"/><pageSetup orientation="landscape" paperSize="9" fitToWidth="1" fitToHeight="0"/></worksheet>`;
 const styles=`<?xml version="1.0"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="#,##0.00&quot; ₸&quot;"/></numFmts><fonts count="3"><font><sz val="11"/><name val="Calibri"/><color rgb="FF173E67"/></font><font><b/><sz val="18"/><name val="Calibri"/><color rgb="FF173E67"/></font><font><b/><sz val="11"/><name val="Calibri"/><color rgb="FFFFFFFF"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF173E67"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="7"><xf fontId="0" fillId="0" borderId="0" numFmtId="0" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf fontId="1" fillId="0" borderId="0" numFmtId="0" xfId="0"/><xf fontId="2" fillId="2" borderId="0" numFmtId="0" xfId="0" applyAlignment="1"><alignment vertical="center" wrapText="1"/></xf><xf fontId="0" fillId="0" borderId="0" numFmtId="0" xfId="0"/><xf fontId="0" fillId="0" borderId="0" numFmtId="164" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment vertical="center" horizontal="right"/></xf><xf fontId="0" fillId="0" borderId="0" numFmtId="0" xfId="0" applyAlignment="1"><alignment wrapText="1" vertical="center"/></xf><xf fontId="0" fillId="0" borderId="0" numFmtId="49" xfId="0" applyNumberFormat="1" applyAlignment="1"><alignment vertical="center" horizontal="left" wrapText="1"/></xf></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
 return zipSync({'[Content_Types].xml':enc(`<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`),'_rels/.rels':enc(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`),'xl/workbook.xml':enc(`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${t('Подборка товаров')}" sheetId="1" r:id="rId1"/></sheets><calcPr calcId="191029" fullCalcOnLoad="1"/></workbook>`),'xl/_rels/workbook.xml.rels':enc(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`),'xl/styles.xml':enc(styles),'xl/worksheets/sheet1.xml':enc(sheet)},{level:6});
}
export async function selectionPdf(data:Selection,locale:Locale,fontBytes:Uint8Array){
 const {PDFDocument,rgb,PDFName,PDFString}=await import('pdf-lib');const {default:fontkit}=await import('@pdf-lib/fontkit');
 const doc=await PDFDocument.create();doc.registerFontkit(fontkit);const font=await doc.embedFont(fontBytes,{subset:true});const chars=new Set(font.getCharacterSet());const clean=(s:unknown)=>Array.from(String(s??'').replace(/[\r\n\t]+/g,' ')).map(c=>chars.has(c.codePointAt(0)!)?c:'?').join('');
 const t=(s:unknown)=>translate(s,locale),ink=rgb(.09,.24,.4),muted=rgb(.38,.43,.49);let page:any,y=0;
 function lines(text:unknown,width:number,size=9){const result:string[]=[];let line='';for(const word of clean(text).split(' ')){if(font.widthOfTextAtSize((line?line+' ':'')+word,size)>width&&line){result.push(line);line=''}for(const ch of (line?' ':'')+word){if(font.widthOfTextAtSize(line+ch,size)>width&&line){result.push(line);line=''}line+=ch}}if(line)result.push(line);return result.length?result:['']}
 function text(s:unknown,x:number,at:number,size=9,color=ink){page.drawText(clean(s),{x,y:at,size,font,color})}
 function newPage(){page=doc.addPage([842,595]);y=552;text('ЭЛЕКТРОКОМПЛЕКТ',36,y,10);text(t('Подборка товаров'),36,y-29,20);y-=52}
 function para(s:unknown,size=9){for(const line of lines(s,770,size)){if(y<45)newPage();text(line,36,y,size,muted);y-=size+5}y-=6}
 function header(){const titles=['№','Наименование','Количество','Цена, ₸','Сумма, ₸','Город','Ссылка на товар'];const widths=[28,240,55,82,88,87,190];page.drawRectangle({x:36,y:y-29,width:770,height:30,color:ink});let x=40;titles.forEach((v,i)=>{lines(t(v),widths[i]-9,8).slice(0,2).forEach((v,j)=>text(v,x,y-11-j*10,8,rgb(1,1,1)));x+=widths[i]});y-=38;return widths}
 newPage();para(`${t('Дата выгрузки')}: ${new Date(data.generatedAt).toLocaleString(locale==='kk'?'kk-KZ':'ru-KZ',{timeZone:'Asia/Almaty'})} · ${t('Город')}: ${t(data.city)}`);para(t(note));para(t('Товары из каталога приведены на языке источника.'));
 const widths=header();
 for(const [i,p]of data.rows.entries()){
  const values=[String(i+1),`${p.name} · ${p.article}`,String(p.count),money(p.price),money(p.price*p.count),t(p.city),p.url];const ls=values.map((v,j)=>lines(v,widths[j]-10,j===6?7:9));const height=Math.max(...ls.map(a=>a.length))*12+15;if(y-height<45){newPage();header()}
  let x=40;ls.forEach((a,j)=>{a.forEach((line,k)=>text(line,x,y-k*12,j===6?7:9));x+=widths[j]});
  if(p.url){const link=doc.context.obj({Type:'Annot',Subtype:'Link',Rect:[616,y-height+10,806,y+9],Border:[0,0,0],A:{Type:'Action',S:'URI',URI:PDFString.of(p.url)}});page.node.addAnnot(doc.context.register(link))}
  y-=height;page.drawLine({start:{x:36,y:y+6},end:{x:806,y:y+6},thickness:.5,color:rgb(.83,.87,.9)});y-=10;
 }
 if(y<85)newPage();y-=12;text(`${t('Итого')}: ${money(sum(data))}`,36,y,14);y-=30;
 if(data.unresolved.length){if(y<100)newPage();para(t('Проверить с менеджером'),13);para(t('Позиции для уточнения не включены в итоговую сумму.'));for(const u of data.unresolved)para(`${u.line} — ${t(u.status)}${u.count?` · ${t('Количество')}: ${u.count}`:''}`)}
 doc.getPages().forEach((p,i)=>p.drawText(`${t('Лист')} ${i+1} / ${doc.getPageCount()}`,{x:735,y:20,size:8,font,color:muted}));doc.setTitle(t('Подборка товаров'));doc.setAuthor('Электрокомплект');return doc.save();
}
